// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mrobot.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MRobotAllocResponse_ERROR_CODE int32

const (
	MRobotAllocResponse_SUCCESS MRobotAllocResponse_ERROR_CODE = 0
)

var MRobotAllocResponse_ERROR_CODE_name = map[int32]string{
	0: "SUCCESS",
}
var MRobotAllocResponse_ERROR_CODE_value = map[string]int32{
	"SUCCESS": 0,
}

func (x MRobotAllocResponse_ERROR_CODE) Enum() *MRobotAllocResponse_ERROR_CODE {
	p := new(MRobotAllocResponse_ERROR_CODE)
	*p = x
	return p
}
func (x MRobotAllocResponse_ERROR_CODE) String() string {
	return proto.EnumName(MRobotAllocResponse_ERROR_CODE_name, int32(x))
}
func (x *MRobotAllocResponse_ERROR_CODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MRobotAllocResponse_ERROR_CODE_value, data, "MRobotAllocResponse_ERROR_CODE")
	if err != nil {
		return err
	}
	*x = MRobotAllocResponse_ERROR_CODE(value)
	return nil
}
func (MRobotAllocResponse_ERROR_CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mrobot_64d5fa4128df2c1a, []int{2, 0}
}

type MRobotFreeResponse_ERROR_CODE int32

const (
	MRobotFreeResponse_SUCCESS MRobotFreeResponse_ERROR_CODE = 0
)

var MRobotFreeResponse_ERROR_CODE_name = map[int32]string{
	0: "SUCCESS",
}
var MRobotFreeResponse_ERROR_CODE_value = map[string]int32{
	"SUCCESS": 0,
}

func (x MRobotFreeResponse_ERROR_CODE) Enum() *MRobotFreeResponse_ERROR_CODE {
	p := new(MRobotFreeResponse_ERROR_CODE)
	*p = x
	return p
}
func (x MRobotFreeResponse_ERROR_CODE) String() string {
	return proto.EnumName(MRobotFreeResponse_ERROR_CODE_name, int32(x))
}
func (x *MRobotFreeResponse_ERROR_CODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MRobotFreeResponse_ERROR_CODE_value, data, "MRobotFreeResponse_ERROR_CODE")
	if err != nil {
		return err
	}
	*x = MRobotFreeResponse_ERROR_CODE(value)
	return nil
}
func (MRobotFreeResponse_ERROR_CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mrobot_64d5fa4128df2c1a, []int{4, 0}
}

type MediaChannel struct {
	Ip                   *string  `protobuf:"bytes,1,req,name=ip" json:"ip,omitempty"`
	Port                 *int32   `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	Ptype                *int32   `protobuf:"varint,3,req,name=ptype" json:"ptype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaChannel) Reset()         { *m = MediaChannel{} }
func (m *MediaChannel) String() string { return proto.CompactTextString(m) }
func (*MediaChannel) ProtoMessage()    {}
func (*MediaChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_mrobot_64d5fa4128df2c1a, []int{0}
}
func (m *MediaChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaChannel.Unmarshal(m, b)
}
func (m *MediaChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaChannel.Marshal(b, m, deterministic)
}
func (dst *MediaChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaChannel.Merge(dst, src)
}
func (m *MediaChannel) XXX_Size() int {
	return xxx_messageInfo_MediaChannel.Size(m)
}
func (m *MediaChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaChannel.DiscardUnknown(m)
}

var xxx_messageInfo_MediaChannel proto.InternalMessageInfo

func (m *MediaChannel) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *MediaChannel) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *MediaChannel) GetPtype() int32 {
	if m != nil && m.Ptype != nil {
		return *m.Ptype
	}
	return 0
}

type MRobotAllocRequest struct {
	Ptype                *int32   `protobuf:"varint,1,req,name=ptype" json:"ptype,omitempty"`
	Callid               *string  `protobuf:"bytes,2,req,name=callid" json:"callid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MRobotAllocRequest) Reset()         { *m = MRobotAllocRequest{} }
func (m *MRobotAllocRequest) String() string { return proto.CompactTextString(m) }
func (*MRobotAllocRequest) ProtoMessage()    {}
func (*MRobotAllocRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mrobot_64d5fa4128df2c1a, []int{1}
}
func (m *MRobotAllocRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MRobotAllocRequest.Unmarshal(m, b)
}
func (m *MRobotAllocRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MRobotAllocRequest.Marshal(b, m, deterministic)
}
func (dst *MRobotAllocRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MRobotAllocRequest.Merge(dst, src)
}
func (m *MRobotAllocRequest) XXX_Size() int {
	return xxx_messageInfo_MRobotAllocRequest.Size(m)
}
func (m *MRobotAllocRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MRobotAllocRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MRobotAllocRequest proto.InternalMessageInfo

func (m *MRobotAllocRequest) GetPtype() int32 {
	if m != nil && m.Ptype != nil {
		return *m.Ptype
	}
	return 0
}

func (m *MRobotAllocRequest) GetCallid() string {
	if m != nil && m.Callid != nil {
		return *m.Callid
	}
	return ""
}

type MRobotAllocResponse struct {
	Code                 *int32        `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg               *string       `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	Callid               *string       `protobuf:"bytes,3,req,name=callid" json:"callid,omitempty"`
	Amedia               *MediaChannel `protobuf:"bytes,4,req,name=amedia" json:"amedia,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MRobotAllocResponse) Reset()         { *m = MRobotAllocResponse{} }
func (m *MRobotAllocResponse) String() string { return proto.CompactTextString(m) }
func (*MRobotAllocResponse) ProtoMessage()    {}
func (*MRobotAllocResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mrobot_64d5fa4128df2c1a, []int{2}
}
func (m *MRobotAllocResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MRobotAllocResponse.Unmarshal(m, b)
}
func (m *MRobotAllocResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MRobotAllocResponse.Marshal(b, m, deterministic)
}
func (dst *MRobotAllocResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MRobotAllocResponse.Merge(dst, src)
}
func (m *MRobotAllocResponse) XXX_Size() int {
	return xxx_messageInfo_MRobotAllocResponse.Size(m)
}
func (m *MRobotAllocResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MRobotAllocResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MRobotAllocResponse proto.InternalMessageInfo

func (m *MRobotAllocResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MRobotAllocResponse) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

func (m *MRobotAllocResponse) GetCallid() string {
	if m != nil && m.Callid != nil {
		return *m.Callid
	}
	return ""
}

func (m *MRobotAllocResponse) GetAmedia() *MediaChannel {
	if m != nil {
		return m.Amedia
	}
	return nil
}

type MRobotFreeRequest struct {
	Callid               *string  `protobuf:"bytes,1,req,name=callid" json:"callid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MRobotFreeRequest) Reset()         { *m = MRobotFreeRequest{} }
func (m *MRobotFreeRequest) String() string { return proto.CompactTextString(m) }
func (*MRobotFreeRequest) ProtoMessage()    {}
func (*MRobotFreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mrobot_64d5fa4128df2c1a, []int{3}
}
func (m *MRobotFreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MRobotFreeRequest.Unmarshal(m, b)
}
func (m *MRobotFreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MRobotFreeRequest.Marshal(b, m, deterministic)
}
func (dst *MRobotFreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MRobotFreeRequest.Merge(dst, src)
}
func (m *MRobotFreeRequest) XXX_Size() int {
	return xxx_messageInfo_MRobotFreeRequest.Size(m)
}
func (m *MRobotFreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MRobotFreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MRobotFreeRequest proto.InternalMessageInfo

func (m *MRobotFreeRequest) GetCallid() string {
	if m != nil && m.Callid != nil {
		return *m.Callid
	}
	return ""
}

type MRobotFreeResponse struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg               *string  `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MRobotFreeResponse) Reset()         { *m = MRobotFreeResponse{} }
func (m *MRobotFreeResponse) String() string { return proto.CompactTextString(m) }
func (*MRobotFreeResponse) ProtoMessage()    {}
func (*MRobotFreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mrobot_64d5fa4128df2c1a, []int{4}
}
func (m *MRobotFreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MRobotFreeResponse.Unmarshal(m, b)
}
func (m *MRobotFreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MRobotFreeResponse.Marshal(b, m, deterministic)
}
func (dst *MRobotFreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MRobotFreeResponse.Merge(dst, src)
}
func (m *MRobotFreeResponse) XXX_Size() int {
	return xxx_messageInfo_MRobotFreeResponse.Size(m)
}
func (m *MRobotFreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MRobotFreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MRobotFreeResponse proto.InternalMessageInfo

func (m *MRobotFreeResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MRobotFreeResponse) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*MediaChannel)(nil), "protos.MediaChannel")
	proto.RegisterType((*MRobotAllocRequest)(nil), "protos.MRobotAllocRequest")
	proto.RegisterType((*MRobotAllocResponse)(nil), "protos.MRobotAllocResponse")
	proto.RegisterType((*MRobotFreeRequest)(nil), "protos.MRobotFreeRequest")
	proto.RegisterType((*MRobotFreeResponse)(nil), "protos.MRobotFreeResponse")
	proto.RegisterEnum("protos.MRobotAllocResponse_ERROR_CODE", MRobotAllocResponse_ERROR_CODE_name, MRobotAllocResponse_ERROR_CODE_value)
	proto.RegisterEnum("protos.MRobotFreeResponse_ERROR_CODE", MRobotFreeResponse_ERROR_CODE_name, MRobotFreeResponse_ERROR_CODE_value)
}

func init() { proto.RegisterFile("mrobot.proto", fileDescriptor_mrobot_64d5fa4128df2c1a) }

var fileDescriptor_mrobot_64d5fa4128df2c1a = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xbf, 0x4b, 0xc4, 0x30,
	0x14, 0xc7, 0x6d, 0xee, 0xae, 0x72, 0xef, 0xaa, 0x68, 0x74, 0xa8, 0x5b, 0x89, 0x0e, 0x9d, 0x6e,
	0xd0, 0xc1, 0x59, 0x6a, 0xdd, 0xca, 0x41, 0x8a, 0xb3, 0xd4, 0xf6, 0xa1, 0x85, 0xb4, 0x2f, 0x26,
	0x71, 0x70, 0xf7, 0x0f, 0x97, 0x26, 0x1c, 0x57, 0x17, 0x71, 0x7a, 0x3c, 0xf8, 0xfe, 0xfa, 0x40,
	0x32, 0x18, 0x7a, 0x25, 0xb7, 0xd5, 0x86, 0x1c, 0xf1, 0xd8, 0x1f, 0x2b, 0xee, 0x21, 0xa9, 0xb0,
	0xeb, 0x9b, 0xe2, 0xbd, 0x19, 0x47, 0x54, 0x1c, 0x80, 0xf5, 0x3a, 0x8d, 0x32, 0x96, 0xaf, 0x79,
	0x02, 0x4b, 0x4d, 0xc6, 0xa5, 0x2c, 0x63, 0xf9, 0x8a, 0x9f, 0xc0, 0x4a, 0xbb, 0x2f, 0x8d, 0xe9,
	0x62, 0x7a, 0xc5, 0x1d, 0xf0, 0x4a, 0x4e, 0x81, 0x0f, 0x4a, 0x51, 0x2b, 0xf1, 0xe3, 0x13, 0xad,
	0x3b, 0x88, 0x22, 0xef, 0x39, 0x85, 0xb8, 0x6d, 0x94, 0xea, 0x3b, 0x9f, 0xb1, 0x16, 0xdf, 0x11,
	0x5c, 0xfc, 0x72, 0x59, 0x4d, 0xa3, 0xc5, 0xa9, 0xa9, 0xa5, 0x6e, 0xe6, 0x42, 0x63, 0x06, 0xfb,
	0x16, 0x5c, 0xb3, 0x94, 0x85, 0xff, 0x6f, 0x20, 0x6e, 0x86, 0x69, 0x74, 0xba, 0xcc, 0x58, 0xbe,
	0xb9, 0xbd, 0x0c, 0x4c, 0x76, 0x3b, 0x27, 0x11, 0x57, 0x00, 0xa5, 0x94, 0x3b, 0xf9, 0x52, 0xec,
	0x1e, 0x4b, 0xbe, 0x81, 0xe3, 0xfa, 0xb9, 0x28, 0xca, 0xba, 0x3e, 0x3b, 0x12, 0xd7, 0x70, 0x1e,
	0x56, 0x3c, 0x19, 0xc4, 0xfd, 0xf4, 0x43, 0x8b, 0xa7, 0x17, 0xd5, 0x1e, 0x30, 0x88, 0xfe, 0xb3,
	0xf4, 0x8f, 0xce, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x23, 0x80, 0xf9, 0x7f, 0x01, 0x00,
	0x00,
}
